apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeswitch-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeswitch-ai
  template:
    metadata:
      labels:
        app: codeswitch-ai
    spec:
      containers:
      - name: codeswitch-ai
        image: 340752818167.dkr.ecr.eu-north-1.amazonaws.com/codeswitch-ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080