apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-collector
  namespace: codeswitch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-collector
  template:
    metadata:
      labels:
        app: result-collector
    spec:
      containers:
      - name: result-collector
        image: codeswitch-ai:latest
        command: ["./result-collector"]
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-service:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: result-collector
  namespace: codeswitch
spec:
  selector:
    app: result-collector
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 