apiVersion: v1
kind: Service
metadata:
  name: frequency-calculator
  namespace: codeswitch
spec:
  selector:
    app: frequency-calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: codeswitch
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP